### ISSUE TITLE
Theme colors not applied

### ISSUE THREAD

**Issue by marcolabreu** [pgbross/vue-material-adapter#165]
# Theme not applied
Editing src/styles/theme.scss for your sample project do not result in a change of colors.

### What vue-material-adapter Version are you using?

> 0.16.8, 0.16.9 and 0.17.0-beta.10 give the same results

### What browser(s) is this bug affecting?

> Safari, Chrome, Firefox

### What OS are you using?

> macOS Catalina 10.15.6

### What are the steps to reproduce the bug?

> 1. In the codebase, cd to `examples/basic-vue-cli`
> 2. _OPTIONAL_: update package.json with `"vue-material-adapter": "^0.16.9"`
> 3. run `npm install`
> 4. edit `examples/basic-vue-cli/src/styles/theme.scss` to change theme colors, for example with:

```scss
@use '@material/theme'  with (
  $primary: #FEDBD0,
  $on-primary: #442C2E,
  $secondary: #FEEAE6,
  $on-secondary: #442C2E,
  $surface: #FFFBFA,
  $on-surface: #442C2E,
  $background: #FFFFFF,
  //$on-background: #442C2E, // Causes an error reproduced bellow
);
```

### What is the expected behavior?

> Color should change, in the case above to Shrine theme.

### What is the actual behavior?

> Colors remain the default ones. 

### Any other information you believe would be useful?

Additionally to running your `examples/basic-vue-cli`, I set up another project from scratch, using the latest versions for all packages in `package.json`, with the exact same result: theme colors not applied. The Github repo is [here](https://github.com/marcolabreu/vue-material-adapter-theming).

A [CodeSandbox](https://codesandbox.io/s/vue-material-adapter-qv4j2) with basically the similar code presents a different issue: the components do not receive any style at all.

### An additional error, probably unrelated

Most likely not related to the issue described above, the use of `$on-background` causes an error on the sass-loader. It's probably an upstream problem, but since I bumped into it, I reproduce it here for the sake of completeness.

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This module was already loaded, so it can't be configured using "with".
   ┌──> node_modules/@material/theme/_index.scss
4  │   @forward "./functions";
   │   ^^^^^^^^^^^^^^^^^^^^^^ new load
   ╵
   ┌──> node_modules/@material/theme/_variables.scss
25 │   @use "./functions";
   │   ━━━━━━━━━━━━━━━━━━ original load
   ╵
   ┌──> vue-material-adapter/examples/basic-vue-cli/src/styles/theme.scss
1  │ ┌ @use '@material/theme'  with (
2  │ │   $primary: #FEDBD0,
3  │ │   $on-primary: #442C2E,
4  │ │   $secondary: #FEEAE6,
5  │ │   $on-secondary: #442C2E,
6  │ │   $surface: #FFFBFA,
7  │ │   $on-surface: #442C2E,
8  │ │   $background: #FFFFFF,
9  │ │   $on-background: #442C2E,
10 │ │ );
   │ └─^ configuration
   ╵
  node_modules/@material/theme/_index.scss 4:1  @use
  stdin 1:1                                     root stylesheet
```

**Comment by pgbross** [comment]
Thank you for a good issue report and your repo.

I will look into this and see what is different as I have a project for a customer which uses this:

```scss
@use '@material/theme'  with (
  $primary: #ffa219,
  $on-primary: #000,
);
```

and the colours change correctly.

**Comment by marcolabreu** [comment]
Thanks for the fast reply. 

I am designing the UX/UI for a client's app. They chose Vue as their framework and I'm proposing the adoption of themed (color, shape, etc) Material Design Web Components on the project. The `vue-material-adapter` project seams very promising to speed up the developing fase, but theming is extremely important. 

**If I may be of further assistance, let me know.** 

BTW, there was a mistake on the original report: using the latest beta with `^0.17.0-beta.10`, actually makes all components disappear which is a completely different issue, maybe expected on the beta. I edited the original post removing that.

Also, I created a [CodeSandbox](https://codesandbox.io/s/vue-material-adapter-qv4j2) with similar code and found a variation of the issue: the components do not receive any style whatsoever.  :o)

**Comment by pgbross** [comment]
So, there are a few things going on here:
1) The main issue on the theme.
2) The additional error. 
3) The use of the new beta release.

When webpack's sass-loader processes the .scss files it sees them as separate items, whereas the `material-components-web` needs the theme to be applied as modules in the scope of the applied theme.

So a fix would be to change `index.js` to import `theme.scss` and have that import the button and textfield files (or perhaps more optimally include the @use statements directly) e.g.:

```js
// index.js
import "./theme.scss";
```
```scss
// theme.scss
@use '@material/theme'  with (
   $primary: #FEDBD0,
   $on-primary: #442C2E,
   $secondary: #FEEAE6,
   $on-secondary: #442C2E,
   $surface: #FFFBFA,
   $on-surface: #442C2E,
   $background: #FFFFFF,
  
);
@use 'button';
@use 'textfield';
```

The additional error is because the `material-components-web` theme package does not have a variable `$on-background`. In [_variables.scss](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_variables.scss) it has:

```scss
@forward './theme-color' show $primary, $on-primary, $accent, $secondary, $on-secondary, $background, $surface, $on-surface, $error, $on-error, $text-colors, $text-emphasis, ink-color-for-fill_, $property-values, prop-value, prop-value, accessible-ink-color, is-valid-theme-prop-value_, text-emphasis;
```

Lastly for the new `v0.17.0-beta-10` you need to include a call to initialise the `@vue/composition-api` library even if you do not use its features as v0.17.0 versions are using it internally (as a stepping stone to a future version using Vue3). e.g in `main.js`:

```js
import "./styles";
import Vue from "vue";
import App from "./App.vue";
import VueCompositionAPI from "@vue/composition-api";

import VueMaterialAdapter from "vue-material-adapter";
Vue.use(VueCompositionAPI);

Vue.config.productionTip = false;
Vue.use(VueMaterialAdapter);

new Vue({
  render: h => h(App)
}).$mount("#app");


Let me know if this fixes things for you.
```

**Comment by marcolabreu** [comment]
Wow, that was super fast, thanks! **Yes, colors are now applied correctly**. I'll experiment later with` 0.17.0-beta-10` following the instructions above.

Further components customizations are also working fine. For example, customizing `button.scss` as
```scss
@use "~@material/button" with (
  $height: 32px
);

@include button.core-styles;
@include button.theme-baseline;
```
also works correctly. Thanks again.

Sorry about the `$on-background` false alarm. It didn't occur to me to check if it was there. I got it from [MDC-103 Tutorial](https://codelabs.developers.google.com/codelabs/mdc-103-web/#2) which actually doesn't mention the MDC version being used.

Can I bother you with an additional theme-related question? :o)

I added a `shape.scss` file to `styles` folder with 
```scss
@use "~@material/shape" with (
  $small-component-radius: 16px,
  $medium-component-radius: 4px,
  $large-component-radius: 0,
);
```
and added `@use 'shape'` to `theme.scss`—before any components, otherwise sass is broken— and it works fine. But it's an all or none proposition affecting everything. What if I want round buttons and squared text fields?

**Comment by pgbross** [comment]
You can theme buttons and other UI components (see [mdc-button](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button)) with SASS variables.

e.g:

```scss
@use '@material/button/mixins' as button;

// ... stuff

.button-task-next {
  --mdc-typography-button-font-weight: 700;

  @include button.container-fill-color(white);
  @include button.height(48px);
  @include button.shape-radius(24px);
  @include button.ink-color(#222);
  @include button.horizontal-padding(18px);

  @include button.disabled-icon-color(red);
}
```
or exactly as documented in the `mdc-button` package above, but I haven't analysed the resultant `.css` files to see if there is duplication if multiple `.scss files` make an `@use "@material/button"; ` calls (my project has an `mdcweb.scss` file that has the `@use mdc-<package>` calls, and a separate `styles.scss` file with the customistations for that project), so you would need to check things were working optimally for you.

```scss
@use "@material/button";
@include button.core-styles;

.button-task-next {
  --mdc-typography-button-font-weight: 700;

  @include button.container-fill-color(white);
  @include button.height(48px);
  @include button.shape-radius(24px);
  @include button.ink-color(#222);
  @include button.horizontal-padding(18px);

  @include button.disabled-icon-color(red);
}
```
and

```html
<mcw-button class="button-task-next">next</mcw-button>
```

And you can customise any other component in a similar way.

**Comment by marcolabreu** [comment]
I see. Much to learn about the sass I still have... :o)

Do you want me to make a PR update the `examples/basic-vue-cli/README.md` to match the above?

And since I still didn't find good advice about dark/light themes, I'll just shoot: what are you using (or what do you recommend) as the best approach to have light and dark themes?

**Comment by pgbross** [comment]
Any PR would be great thanks.

Switching Dark/Light themes are an area I haven't really found a good solution/example yet (ie. as far as I can tell material-components-web is relatively easily themeable with a single theme as shown above, but when it comes to switching I think it requires each component to be customised in the CSS).

So, the basic way of having a switchable theme just now would be to have, say, the `<body/>` element have a class="theme-light" or class="theme-dark" that you could switch in however the user selects the theme. Then in the css for each component you would have to define appropriate colours.

e.g.
```scss
.theme-light .mdc-button {
@include button.ink-color(#222);
@include button.container-fill-color(#fff);
}

.theme-dark .mdc-button {
@include button.ink-color(#eee);
@include button.container-fill-color(#222);
}
```
It would be possible to develop some mixins to help with this I am sure, but I haven't had the time to do this.

You may also get some/more mileage with using the CSS custom properties - I could imagine it might be possible to set up a couple of classes/definintions in css that define a set of CSS properties `--mdc-theme-primary`, `--mdc-theme-secondary` etc, then since they are inherited in the normal CSS way that may allow simple switching without having to customise every component in CSS - but that would take more experimentation. This [theming guide](https://material.io/develop/web/docs/theming) might be inspiration on how to start down that route.

Sorry I have no specific recommendations, but hopefully that is enough to give you something to work from, and if you do develop any examples that might be of use to others, then they could be made into PRs and added to the repo.

**Comment by marcolabreu** [comment]
Just to clarify, my concern for a dark theme is to provide auto theme switch based on `@media (prefers-color-scheme: dark)`.

So I guess the approach you suggested above would work as in 
```scss
.mdc-button {
  @media only screen and (prefers-color-scheme: dark) {
    @include button.ink-color(#eee);
    @include button.container-fill-color(#222);
  } 
}
```

And/or it could be detected app wide with JavaScript if we want to change non-CSS aspects. Maybe something like
```javascript
window
  .matchMedia("(prefers-color-scheme: dark)")
  .addEventListener("change", e => {
    store.preferDark = e.matches;
  });
```

The lack of dark mode support in the context of Material Design Web Components actually surprised me. Especially considering how many browser support it [according to caniuse.com](https://caniuse.com/#search=color-schem).
