### ISSUE TITLE
How to pass an attribute?

### ISSUE THREAD

**Issue by SandHilt** [pgbross/vue-material-adapter#46]
Hey, i'm trying put an class or id attribute to MCW Components.
How to pass attributes?

Example:
```html
<mcw-layout-grid class="my-class" />
```

**Comment by pgbross** [comment]
Generally Vue components transparently pass additional attributes such as the id and class to the root element of the component. For Vue functional components it turns out this is not true, and the `mcw-layout-grid` component is a functional component.

This is an oversight and I will update the component so that it works as you expect passing the additional static attributes.

**Comment by pgbross** [comment]
Fixed in 0.10.0 and later.
